version: '3'
services:
  app:
    build: .
    expose:
      - 8080
    links:
      - redis
    environment:
      - PORT=8080
      - REDIS_URL=redis:6379
  redis:
    image: "redis:4-alpine"
  proxy:
    build: nginx
    ports:
      - "8398:80"
    links:
      - app
